#!/bin/bash
#
# iotsysd        init file for starting up the iotsysd daemon
#
# chkconfig:   - 96 10
# description: Starts and stops the iotsysd daemon.

# Source function library.
. /etc/rc.d/init.d/functions

name="iotsysd"
exec="/usr/local/bin/$name"
pidfile="/var/run/iotsysd/iotsysd.pid"
IOTSYSD_CONFIG="/etc/iotsysd/iotsysd.properties"
owner=nobody

lockfile=/var/lock/subsys/iotsysd

start() {
    [ -f $IOTSYSD_CONFIG ] || exit 6
    [ -x $exec ] || exit 5
    echo -n $"Starting $name: "
    daemon --user ${owner} "$exec"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $name: "
    killproc -p $pidfile $name
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    false
}

rh_status() {
    status -p $pidfile $name
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart)"
        exit 2
esac
exit $?
